name: Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  publish:
    name: Build, pack and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Run _build
      run: >-
        dotnet pack src/ThirdPartyNoticesGenerator.sln --configuration Release -o "./packages";
      shell: pwsh

    - name: Run _build
      run: >-
        dotnet tool install -g Kuinox.NupkgDeterministicator;
        $build_date = $(git show -s --date=iso-strict --format=%cd);
        Get-ChildItem "./packages" -Filter *.nupkg | 
        Foreach-Object {
          NupkgDeterministicator $_.FullName $build_date
        }
      shell: pwsh

    - name: Push to NuGet
      run: dotnet nuget push "./packages/*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://www.nuget.org
      shell: pwsh

    - name: Push to GPR
      run: |
           for f in ./packages/*.nupkg
           do
             curl -vX PUT -u "vslee:${{secrets.GITHUB_TOKEN}}" -F package=@$f https://nuget.pkg.github.com/Aragas/
           done
      shell: bash
